# Generated by Django 4.0.1 on 2022-02-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=100)),
                ('pcontent', models.TextField()),
                ('pdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('purl', models.CharField(max_length=100)),
                ('post_img', models.ImageField(upload_to='post/')),
                ('pauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iblog.author')),
                ('pcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iblog.category')),
            ],
        ),
    ]
