# Generated by Django 4.0.1 on 2022-02-17 12:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pcontent',
            field=tinymce.models.HTMLField(),
        ),
    ]
