# Generated by Django 4.0.1 on 2022-02-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0002_alter_post_pcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='iblog.post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iblog.user')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
